version: '3.8'

services:

  backend:
    image: gps1mx/go-challenge:1
    container_name: backend
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      BACKEND_ADDRESS: "backend"

  frontend:
    image: gps1mx/react-challenge:1
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
